apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: company

resources:
  - namespace.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

# GitHub Actions 가 빌드 후 newName/newTag 를 자동 갱신
images:
  - name: company-backend
    newName: company-backend
    newTag: latest
  - name: company-frontend
    newName: company-frontend
    newTag: latest
